name: empowerher
description: "A new Flutter project."

publish_to: 'none' # Prevent accidental publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.7.0
  firebase_auth: ^5.3.2
  cloud_firestore: ^5.4.5
  firebase_analytics: ^11.3.4
  firebase_storage: ^12.3.5
  image_picker: ^1.1.2
  geolocator: ^12.0.0
  dialogflow_grpc: ^0.2.9 # Add Dialogflow for AI support
  google_maps_flutter: ^2.9.0 # Google Maps for resource locations
  flutter_local_notifications: ^18.0.1 # Push notifications support
  provider: ^6.1.2 # State management for Firebase services
  google_sign_in: ^6.2.2 # Google Sign-in, if needed
  firebase_messaging: ^15.1.5
  googleapis: ^13.2.0
  googleapis_auth: ^1.6.0
  uuid: 3.0.7

flutter:
  uses-material-design: true

assets:
  - assets/empowerher-441416-b39d1592de5c.json

# Specify images or other files you want to add
  # Folder for any custom UI assets, like icons or graphics

# Optional: include fonts
fonts:
  - family: Poppins
    fonts:
      - asset: assets/fonts/Poppins-Regular.ttf
      - asset: assets/fonts/Poppins-Bold.ttf
